// All the items in the shop can be updated here
let shopItemsData = [
  {
    id: "candle1",
    name: "Candle 1",
    price: 100,
    desc: "Price for 1 mid-sized pillar candle",
    img: "../Images/candle1.jpg",
  },
  {
    id: "candle2",
    name: "Candle 2",
    price: 650,
    desc: "Price for 1 large-sized pillar candle",
    img: "../Images/candle3.jpg",
  },
  {
    id: "candle3",
    name: "Candle 3",
    price: 35,
    desc: "Price for 1 dinner candle",
    img: "../Images/candle4.jpg",
  },
  {
    id: "box1",
    name: "Box 1",
    price: 45,
    desc: "Milk carton party pack box",
    img: "../Images/box1.jpg",
  },
  {
    id: "box2",
    name: "Box 2",
    price: 45,
    desc: "Rounded party pack box",
    img: "../Images/box2.jpg",
  },
  {
    id: "box3",
    name: "Box 3",
    price: 45,
    desc: "Heart party pack box",
    img: "../Images/box3.jpg",
  },
  {
    id: "pringles1",
    name: "Pringles 1",
    price: 55,
    desc: "boy-themed chip box",
    img: "../Images/pringles1.jpg",
  },
  {
    id: "pringles",
    name: "Pringles 2",
    price: 55,
    desc: "girl-themed chip box",
    img: "../Images/pringles2.jpg",
  },
  {
    id: "pringles3",
    name: "Pringles 3",
    price: 50,
    desc: "gender neutral-themed chip box",
    img: "../Images/pringles3.jpg",
  },
  {
    id: "tray1",
    name: "Tray 1",
    price: 40,
    desc: "simple tray box box",
    img: "../Images/tray1.jpg",
  },
  {
    id: "tray2",
    name: "Tray 2",
    price: 48,
    desc: "3D tray box box",
    img: "../Images/tray2.jpg",
  },
  {
    id: "tray3",
    name: "Tray 3",
    price: 48,
    desc: "printed 3D tray box box",
    img: "../Images/tray3.jpg",
  },

];